### ISSUE TITLE
Game mode: survive as long as possible

### ISSUE THREAD

**Issue by lahramon** [MrGreenTea/gmtk-jam-2024#34]
Only the smallest survive! 
Add game mode where enemies are constantly spawning (at current scale level) while world is constantly shrinking (or equivalently, player is growing). Player needs to kill enemies to become smaller again. If player gets too big, they are slapped and its game over. High score time can be tracked for improvement

**Comment by MrGreenTea** [comment]
Done: 6bfc6df03d85824410a3d97074f13b2e7ccd116e
